apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
spec:
  storageClassName: nfs-class
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/xiaohao/test$path
    server: $nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
spec:
 storageClassName: nfs-class
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---
